; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
;
; Build dist\Comfy Launcher first with "packaging\windows\Comfy Launcher.spec",
; then compile this script (Inno Setup 6). Paths are relative to this file, and
; the version is read from version.py; the installer lands in dist\.

#define RepoRoot AddBackslash(SourcePath) + "..\.."
#define VersionFile FileOpen(RepoRoot + "\version.py")
#define VersionLine FileRead(VersionFile)
#expr FileClose(VersionFile)
#define VersionStart Pos('"', VersionLine) + 1
#define VersionEnd RPos('"', VersionLine)

#define MyAppName "Comfy Launcher"
#define MyAppVersion Copy(VersionLine, VersionStart, VersionEnd - VersionStart)
#define MyAppPublisher "nondeletable"
#define MyAppURL "https://www.nondeletable.com/"
#define MyAppExeName "Comfy Launcher.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{91F944B6-A4A8-427C-B953-E4E0C251AC08}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
LicenseFile={#RepoRoot}\LICENSE.txt
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir={#RepoRoot}\dist
OutputBaseFilename=ComfyLauncher_v{#MyAppVersion}_setup
SetupIconFile={#RepoRoot}\assets\icons\icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#RepoRoot}\dist\Comfy Launcher\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#RepoRoot}\dist\Comfy Launcher\_internal\*"; DestDir: "{app}\_internal"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#SourcePath}THIRD-PARTY-NOTICES.txt"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
