"""Loader for the bundled ComfyUI startup-flags catalog (assets/data/flags.json).

The catalog is generated by ``tools/gen_flags.py`` and shown in the flags picker.
Loading never raises: a missing or malformed file yields an empty catalog so the
picker degrades to plain manual entry instead of crashing.
"""

from __future__ import annotations

import json

from config import FLAGS_JSON_PATH


def load_flags_catalog(path: str | None = None) -> dict:
    """Return the flags catalog as ``{"groups": [...]}``.

    On any read/parse error returns ``{"groups": []}``.
    """
    path = path or FLAGS_JSON_PATH
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except (FileNotFoundError, OSError, json.JSONDecodeError):
        return {"groups": []}

    groups = data.get("groups") if isinstance(data, dict) else None
    if not isinstance(groups, list):
        return {"groups": []}
    return {"groups": groups}


def iter_flags(catalog: dict | None = None):
    """Yield each flag dict across all groups (loads the catalog if not given)."""
    catalog = catalog or load_flags_catalog()
    for group in catalog.get("groups", []):
        for flag in group.get("flags", []):
            yield flag
